# HEY BUDY TODAY IS MY NEW BOOK FOR
# COME TO LEARN THE PYHTOB AT NEW WAY
# THANK YOU


#I can take  
"""     
HI BUDY

"""


# Docstrings  
def add(x,y):
    """
    This code is add two number in python 
    
    """
    print("Sum=>",x+y)
    
    
def message_box():
    '''This function is work for a message display 
        to how to work a def keyword anything can written is this documnetation string
    '''
    print("Welcome to python")
    
add(10,90)
print(add.__doc__)
print(message_box.__doc__)